web-front:
#   command: --version
    cpu_shares: 0
    dns:
        - 8.8.8.8
        - 8.8.4.4
    dns_search:
        - kurron.org
        - transparent.com
#   entrypoint: /foo/bar
    environment:
        BAR: 'true'
    extra_hosts:
        - "master:192.168.1.1"
        - "slave:192.168.1.254"
    hostname: kara-el
    image: nginx:latest
    labels:
        org.kurron.example.dictionary: "dictionary"
#   links:
    log_driver: json-file
    log_opt:
        max-size: 1g
    # ECS cannot handle the 256m form
    mem_limit: 256000000
    ports:
        - 9876:80
    privileged: false
    read_only: false
#   security_opt:
    # ECS cannot seem to handle this form
#   ulimits:
#       nproc: 65535
    user: root
    volumes:
        - /tmp:/does-not-exist
#   volumes_from:
    working_dir: /

web-back:
#   command: --version
    cpu_shares: 0
    dns:
        - 8.8.8.8
        - 8.8.4.4
    dns_search:
        - kurron.org
        - transparent.com
#   entrypoint: /foo/bar
    environment:
        BAR: 'true'
    extra_hosts:
        - "master:192.168.1.1"
        - "slave:192.168.1.254"
    hostname: zor-el
    image: nginx:latest
    labels:
        org.kurron.example.dictionary: "dictionary"
#   links:
    log_driver: json-file
    log_opt:
        max-size: 1g
    # ECS cannot handle the 256m form
    mem_limit: 512000000
    ports:
        - 5432:80
    privileged: false
    read_only: false
#   security_opt:
    # ECS cannot seem to handle this form
#   ulimits:
#       nproc: 65535
    user: root
    volumes:
        - /tmp:/does-not-exist
#   volumes_from:
    working_dir: /

