ecs:
    build: .
    net: "host"
    volumes:
        - /home/vagrant:/home/developer
    environment:
        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
        AWS_REGION: $AWS_REGION
    user: 1000:1000
    stdin_open: true
    tty: true
    command: help
